from __future__ import annotations

import base64
import hashlib
import ipaddress
import os
import shlex
from contextlib import asynccontextmanager
from pathlib import Path
from urllib.parse import unquote, urlsplit, urlunsplit

from fastapi import FastAPI, HTTPException, Request
from fastapi.responses import FileResponse, HTMLResponse, JSONResponse, Response, StreamingResponse
from fastapi.staticfiles import StaticFiles

from .config import ConfigurationError, Settings, SourceConfig, load_settings
from .gateway import Gateway, PackageNotFound, StreamingCacheResult, UpstreamUnavailable
from .importer import PIP_IMPORT_SOURCE
from .pypi import InvalidProject, PypiGateway
from .store import CacheStore, UnsafePathError
from .sync import ClientSync, SyncError


class DynamicSourceError(ValueError):
    pass


def _decode_dynamic_upstream(token: str) -> str:
    if not token or len(token) > 4096:
        raise DynamicSourceError("Invalid dynamic source token")
    try:
        padded = token + "=" * (-len(token) % 4)
        raw = base64.urlsafe_b64decode(padded.encode("ascii")).decode("utf-8")
    except (UnicodeDecodeError, ValueError):
        raise DynamicSourceError("Invalid dynamic source token") from None
    if len(raw) > 2048:
        raise DynamicSourceError("Dynamic source URL is too long")
    parsed = urlsplit(raw)
    if parsed.scheme != "https" or not parsed.hostname or parsed.username or parsed.password:
        raise DynamicSourceError("Dynamic PyPI sources must be HTTPS URLs without credentials")
    if parsed.query or parsed.fragment:
        raise DynamicSourceError("Dynamic PyPI source URL cannot contain query or fragment")
    host = parsed.hostname.lower().rstrip(".")
    try:
        ipaddress.ip_address(host)
    except ValueError:
        pass
    else:
        raise DynamicSourceError("Dynamic PyPI source must use an approved hostname, not an IP address")
    path = parsed.path.rstrip("/")
    if ".." in unquote(path).split("/"):
        raise DynamicSourceError("Dynamic PyPI source path is unsafe")
    try:
        port = parsed.port
    except ValueError as exc:
        raise DynamicSourceError("Dynamic PyPI source port is invalid") from exc
    netloc = host if port in (None, 443) else f"{host}:{port}"
    return urlunsplit(("https", netloc, path, "", ""))


def _decode_client_origin(token: str) -> str:
    if not token:
        return ""
    if len(token) > 8192:
        raise SyncError("Origin token is too long")
    try:
        padded = token + "=" * (-len(token) % 4)
        return base64.urlsafe_b64decode(padded.encode("ascii")).decode("utf-8")
    except (UnicodeDecodeError, ValueError) as exc:
        raise SyncError("Invalid origin token") from exc


def _client_revision(settings: Settings) -> str:
    """Return the deployed client bundle revision.

    A deployment may provide ``PKGRELAY_RELEASE`` with its Git commit.  The
    content digest remains a reliable fallback for local, uncommitted builds.
    """
    release = os.getenv("PKGRELAY_RELEASE", "").strip()
    if release:
        return f"git:{release}"
    digest = hashlib.sha256()
    client_root = Path(__file__).parents[1] / "client"
    for name in ("pip-wrapper.sh", "conda-wrapper.sh", "cache-sync.sh", "client-update.sh"):
        digest.update(name.encode())
        digest.update((client_root / name).read_bytes())
    for source in settings.sources.values():
        if source.kind == "conda":
            digest.update(source.name.encode())
            digest.update("\0".join(source.upstreams).encode())
    return f"bundle:{digest.hexdigest()[:16]}"


def _bootstrap_script(settings: Settings, cache_url: str, revision: str) -> str:
    wrapper = (Path(__file__).parents[1] / "client" / "pip-wrapper.sh").read_text()
    conda_wrapper = (Path(__file__).parents[1] / "client" / "conda-wrapper.sh").read_text()
    cache_sync = (Path(__file__).parents[1] / "client" / "cache-sync.sh").read_text()
    client_update = (Path(__file__).parents[1] / "client" / "client-update.sh").read_text()
    conda_channels = [
        source.name
        for source in settings.sources.values()
        if source.kind == "conda"
    ]
    conda_uninstall_commands = "\n".join(
        f'    conda config --file "$conda_config" --remove channels "${{cache_url%/}}/get/{shlex.quote(channel)}" >/dev/null 2>&1 || true'
        for channel in conda_channels
    )
    conda_channels_file = "\n".join(
        f"{cache_url.rstrip('/')}/get/{channel}" for channel in conda_channels
    )
    return f'''#!/usr/bin/env bash
# Generated by PkgRelay. Interactive user-level setup only.
set -euo pipefail

cache_url={shlex.quote(cache_url)}
client_revision={shlex.quote(revision)}
client_dir="${{XDG_DATA_HOME:-$HOME/.local/share}}/pkgrelay"
legacy_client_dir="${{XDG_DATA_HOME:-$HOME/.local/share}}/conda-cache"
bashrc="$HOME/.bashrc"
timestamp=$(date +%Y%m%d%H%M%S)
state_dir="$client_dir/state"
update_mode=0
case "${{1:-}}" in
  "") ;;
  --update) update_mode=1 ;;
  *) echo "Usage: setenv.sh [--update]" >&2; exit 2 ;;
esac

if [[ -t 1 ]]; then
  C_RESET='\033[0m'; C_BOLD='\033[1m'; C_BLUE='\033[38;5;39m'
  C_GREEN='\033[38;5;40m'; C_YELLOW='\033[38;5;220m'; C_RED='\033[38;5;203m'
else
  C_RESET=''; C_BOLD=''; C_BLUE=''; C_GREEN=''; C_YELLOW=''; C_RED=''
fi
title() {{ printf '\n%b\n' "${{C_BOLD}}${{C_BLUE}}== $* ==${{C_RESET}}"; }}
ok() {{ printf '%b\n' "${{C_GREEN}}✓ $*${{C_RESET}}"; }}
skip() {{ printf '%b\n' "${{C_RED}}- $*${{C_RESET}}"; }}

migrate_legacy_client() {{
  [[ "$legacy_client_dir" != "$client_dir" ]] || return 0
  local migrated=0
  if [[ -f "$bashrc" ]] && grep -Fq '# >>> conda-cache ' "$bashrc"; then
    cp -a "$bashrc" "$bashrc.pkgrelay-backup.$timestamp"
    sed -i '/# >>> conda-cache pip wrapper >>>/,/# <<< conda-cache pip wrapper <<</d' "$bashrc"
    sed -i '/# >>> conda-cache conda wrapper >>>/,/# <<< conda-cache conda wrapper <<</d' "$bashrc"
    migrated=1
  fi
  if [[ -r "$legacy_client_dir/state/pip-index.before" ]]; then
    install -d -m 0755 "$state_dir"
    [[ -f "$state_dir/pip-index.before" ]] || cp -a "$legacy_client_dir/state/pip-index.before" "$state_dir/pip-index.before"
  fi
  if [[ -d "$legacy_client_dir" ]]; then
    rm -f "$legacy_client_dir/pip-wrapper.sh" "$legacy_client_dir/conda-wrapper.sh" \
      "$legacy_client_dir/cache-sync.sh" "$legacy_client_dir/client.conf" "$legacy_client_dir/conda-channels.conf" "$legacy_client_dir/pip-sources.conf"
    rm -f "$legacy_client_dir/state/pip-index.before"
    rmdir "$legacy_client_dir/state" 2>/dev/null || true
    rmdir "$legacy_client_dir" 2>/dev/null || true
    migrated=1
  fi
  if [[ "$migrated" == 1 ]]; then
    ok "已迁移旧版客户端配置。"
  fi
}}

uninstall_cache_client() {{
  title "卸载当前用户的缓存配置"
  if [[ -f "$bashrc" ]]; then
    cp -a "$bashrc" "$bashrc.pkgrelay-backup.$timestamp"
    sed -i '/# >>> pkgrelay pip wrapper >>>/,/# <<< pkgrelay pip wrapper <<</d' "$bashrc"
    sed -i '/# >>> pkgrelay conda wrapper >>>/,/# <<< pkgrelay conda wrapper <<</d' "$bashrc"
    ok "已从 $bashrc 移除缓存包装器标记，并创建备份。"
  else
    skip "未找到 $bashrc；无需移除 Shell 标记。"
  fi

  if command -v conda >/dev/null 2>&1 && [[ -f "$HOME/.condarc" ]]; then
    conda_config="$HOME/.condarc"
    cp -a "$conda_config" "$conda_config.pkgrelay-backup.$timestamp"
{conda_uninstall_commands}
    if grep -Fqx "channel_alias: ${{cache_url%/}}/get" "$conda_config"; then
      conda config --file "$conda_config" --remove-key channel_alias >/dev/null 2>&1 || true
    fi
    ok "已移除当前用户 .condarc 中指向此缓存站的 Channel。"
  else
    skip "未找到当前用户 .condarc 或 conda；未修改 Conda 配置。"
  fi

  if command -v python3 >/dev/null && python3 -m pip --version >/dev/null 2>&1; then
    if [[ -r "$state_dir/pip-index.before" ]]; then
      # This file is created by this script before its first install and only
      # contains shell-quoted values written with printf %q.
      # shellcheck disable=SC1090
      source "$state_dir/pip-index.before"
      if [[ "${{PIP_INDEX_PRESENT:-0}}" == "1" ]]; then
        python3 -m pip config --user set global.index-url "$PIP_INDEX_VALUE" >/dev/null
      else
        python3 -m pip config --user unset global.index-url >/dev/null 2>&1 || true
      fi
      ok "已恢复安装前记录的 pip index-url。"
    else
      pip_index=$(python3 -m pip config --user get global.index-url 2>/dev/null || true)
      if [[ "$pip_index" == "${{cache_url%/}}/get/pypi/pypi/simple" ]]; then
        python3 -m pip config --user unset global.index-url >/dev/null 2>&1 || true
        ok "已移除当前用户 pip 的缓存站 index-url。"
      else
        skip "未找到安装前记录；当前 pip index-url 保持不变。"
      fi
    fi
  fi

  rm -f "$client_dir/pip-wrapper.sh" "$client_dir/conda-wrapper.sh" \
    "$client_dir/client-update.sh" \
    "$client_dir/cache-sync.sh" "$client_dir/client.conf" "$client_dir/conda-channels.conf" "$client_dir/pip-sources.conf"
  rm -f "$state_dir/pip-index.before"
  rmdir "$state_dir" 2>/dev/null || true
  rmdir "$client_dir" 2>/dev/null || true
  ok "已删除当前用户的缓存客户端文件。请执行 exec bash -l 或重新登录以使当前 Shell 生效。"
}}

if [[ "$update_mode" == 1 ]]; then
  setup_action=1
else
  title "缓存客户端"
  printf '%b\n' "缓存站：${{C_BOLD}}$cache_url${{C_RESET}}"
  printf '%b\n' "${{C_BOLD}}1) 安装：接入缓存层${{C_RESET}}"
  printf '%b\n' "${{C_BOLD}}2) 卸载：移除缓存层并恢复已记录的配置${{C_RESET}}"
  read -r -p "${{C_YELLOW}}请选择 [1/2]：${{C_RESET}}" setup_action
  case "$setup_action" in
    1) ;;
    2) uninstall_cache_client; exit 0 ;;
    *) skip "无效选择，未做任何修改。"; exit 2 ;;
  esac
fi
migrate_legacy_client
install -d -m 0755 "$client_dir"
cat > "$client_dir/pip-wrapper.sh" <<'PKGRELAY_WRAPPER'
{wrapper}PKGRELAY_WRAPPER
printf 'PKGRELAY_URL=%q\nPKGRELAY_CLIENT_REVISION=%q\n' "${{cache_url%/}}" "$client_revision" > "$client_dir/client.conf"
cat > "$client_dir/cache-sync.sh" <<'PKGRELAY_SYNC'
{cache_sync}PKGRELAY_SYNC
chmod 0755 "$client_dir/cache-sync.sh"
cat > "$client_dir/client-update.sh" <<'PKGRELAY_UPDATE'
{client_update}PKGRELAY_UPDATE
chmod 0755 "$client_dir/client-update.sh"
if ! grep -Fq '# >>> pkgrelay pip wrapper >>>' "$bashrc" 2>/dev/null; then
  [[ -f "$bashrc" ]] && cp -a "$bashrc" "$bashrc.pkgrelay-backup.$timestamp"
  cat >> "$bashrc" <<PKGRELAY_BASHRC

# >>> pkgrelay pip wrapper >>>
[[ -r "$client_dir/pip-wrapper.sh" ]] && source "$client_dir/pip-wrapper.sh"
# <<< pkgrelay pip wrapper <<<
PKGRELAY_BASHRC
  ok "已安装 pip 重写器，并向 $bashrc 追加一条 source 配置。"
else
  ok "已刷新 pip 客户端文件。"
fi

title "Conda 命令缓存包装器"
if command -v conda >/dev/null 2>&1; then
  install -d -m 0755 "$client_dir"
cat > "$client_dir/conda-wrapper.sh" <<'PKGRELAY_CONDA_WRAPPER'
{conda_wrapper}PKGRELAY_CONDA_WRAPPER
  cat > "$client_dir/conda-channels.conf" <<'PKGRELAY_CONDA_CHANNELS'
{conda_channels_file}
PKGRELAY_CONDA_CHANNELS
  if ! grep -Fq '# >>> pkgrelay conda wrapper >>>' "$bashrc" 2>/dev/null; then
    [[ -f "$bashrc" ]] && cp -a "$bashrc" "$bashrc.pkgrelay-backup.$timestamp"
    cat >> "$bashrc" <<PKGRELAY_CONDA_BASHRC

# >>> pkgrelay conda wrapper >>>
[[ -r "$client_dir/conda-wrapper.sh" ]] && source "$client_dir/conda-wrapper.sh"
# <<< pkgrelay conda wrapper <<<
PKGRELAY_CONDA_BASHRC
  fi
  ok "已安装 Conda 包装器。"
else
  skip "未找到 conda；未安装 Conda 包装器。"
fi

if ! command -v python3 >/dev/null || ! python3 -m pip --version >/dev/null 2>&1; then
  exit 0
fi
install -d -m 0755 "$state_dir"
if [[ ! -f "$state_dir/pip-index.before" ]]; then
  previous_pip_index=$(python3 -m pip config --user get global.index-url 2>/dev/null || true)
  if [[ -n "$previous_pip_index" && "$previous_pip_index" != "${{cache_url%/}}/get/pypi/pypi/simple" ]]; then
    {{ printf 'PIP_INDEX_PRESENT=1\n'; printf 'PIP_INDEX_VALUE=%q\n' "$previous_pip_index"; }} > "$state_dir/pip-index.before"
  else
    printf 'PIP_INDEX_PRESENT=0\n' > "$state_dir/pip-index.before"
  fi
fi
python3 -m pip config --user set global.index-url "${{cache_url%/}}/get/pypi/pypi/simple"
ok "已接入 pip 缓存层。"
if [[ "$update_mode" != 1 ]]; then
  read -r -p "同步并清理当前用户本地包缓存？ [y/N] " cleanup_action
  if [[ "$cleanup_action" =~ ^[Yy]$ ]]; then
    "$client_dir/cache-sync.sh" --prune
  fi
fi
if [[ "$update_mode" == 1 ]]; then
  ok "PkgRelay 客户端已更新至 $client_revision。"
else
  ok "执行：source $client_dir/pip-wrapper.sh && source $client_dir/conda-wrapper.sh"
fi
'''


def create_app(settings: Settings | None = None) -> FastAPI:
    settings = settings or load_settings()
    store = CacheStore(
        settings.cache_dir,
        {**{name: source.pool for name, source in settings.sources.items()}, "import-conda": "conda", PIP_IMPORT_SOURCE: "pip"},
    )
    gateway = Gateway(store)
    pypi_gateway = PypiGateway(store, gateway, settings.sources)
    client_sync = ClientSync(settings, store)

    def dynamic_source(source_id: str) -> SourceConfig | None:
        row = store.get_dynamic_pypi_source(source_id)
        if row is None:
            return None
        return SourceConfig(
            name=str(row["source_id"]),
            upstreams=(str(row["upstream_url"]),),
            metadata_ttl_seconds=0,
            kind="pypi",
            index_path_template="{project}/",
        )

    def pypi_source(source_id: str) -> SourceConfig | None:
        source = settings.sources.get(source_id)
        if source and source.kind == "pypi":
            return source
        if source_id == PIP_IMPORT_SOURCE:
            # Imported files are always resolved from a pre-existing local
            # blob; the placeholder is never contacted for a valid link.
            return SourceConfig(name=PIP_IMPORT_SOURCE, upstreams=("https://pypi.org",), kind="pypi")
        return dynamic_source(source_id)

    async def pypi_index_response(request: Request, source: SourceConfig, project: str) -> HTMLResponse:
        try:
            content, cache_status = await pypi_gateway.simple_index(
                source, project, str(request.base_url).rstrip("/")
            )
        except InvalidProject as exc:
            raise HTTPException(status_code=400, detail=str(exc)) from exc
        except PackageNotFound as exc:
            raise HTTPException(status_code=404, detail=f"Python package not found: {exc}") from exc
        except UpstreamUnavailable as exc:
            raise HTTPException(status_code=502, detail=f"All upstreams failed: {exc}") from exc
        return HTMLResponse(
            content,
            headers={"X-Cache": cache_status, "Cache-Control": f"public, max-age={source.metadata_ttl_seconds}"},
        )

    @asynccontextmanager
    async def lifespan(_: FastAPI):
        yield
        store.close()

    app = FastAPI(title="PkgRelay", version="0.1.0", lifespan=lifespan)
    app.state.settings = settings
    app.state.store = store
    app.state.gateway = gateway
    web_root = Path(__file__).parent / "web"
    app.mount("/assets", StaticFiles(directory=web_root), name="assets")

    @app.get("/healthz")
    async def healthz() -> dict[str, object]:
        return {"status": "ok", "sources": sorted(settings.sources)}

    @app.get("/", include_in_schema=False)
    async def dashboard() -> FileResponse:
        return FileResponse(web_root / "index.html", media_type="text/html")

    @app.get("/bootstrap/setenv.sh", include_in_schema=False)
    async def bootstrap_setenv(request: Request) -> Response:
        return Response(
            _bootstrap_script(settings, str(request.base_url).rstrip("/"), _client_revision(settings)),
            media_type="text/x-shellscript",
            headers={"Content-Disposition": "attachment; filename=setenv.sh", "Cache-Control": "no-store"},
        )

    @app.get("/bootstrap/manifest.json", include_in_schema=False)
    async def bootstrap_manifest(request: Request) -> dict[str, object]:
        base_url = str(request.base_url).rstrip("/")
        return {
            "revision": _client_revision(settings),
            "installer": f"{base_url}/bootstrap/setenv.sh",
            "update_interval_seconds": 21600,
        }

    @app.get("/api/v1/status")
    async def status() -> dict[str, object]:
        return {
            "status": "ok",
            "cache_dir": str(settings.cache_dir),
            "import_mode": "host-side-only",
            "cache": store.statistics(),
        }

    @app.get("/api/v1/sources")
    async def list_sources() -> dict[str, object]:
        dynamic_sources = [
            {
                "name": str(row["source_id"]),
                "upstreams": (str(row["upstream_url"]),),
                "metadata_ttl_seconds": 0,
                "kind": "pypi",
                "dynamic": True,
            }
            for row in store.iter_dynamic_pypi_sources()
        ]
        return {
            "sources": [
                {
                    "name": source.name,
                    "upstreams": source.upstreams,
                    "metadata_ttl_seconds": source.metadata_ttl_seconds,
                    "kind": source.kind,
                }
                for source in settings.sources.values()
            ] + dynamic_sources
        }

    def client_sync_enabled() -> None:
        if not settings.client_sync_enabled:
            raise HTTPException(status_code=403, detail="Client cache sync is disabled")

    def client_sync_response(record) -> dict[str, object]:
        return {
            "status": "ready",
            "pool": record.pool,
            "source_id": record.source_id,
            "path": record.path,
            "sha256": record.sha256,
            "size": record.size,
        }

    @app.get("/api/v1/client-sync/{kind}/{sha256}")
    async def client_sync_check(kind: str, sha256: str, filename: str, origin: str = ""):
        client_sync_enabled()
        try:
            record = client_sync.register(kind, sha256, filename, _decode_client_origin(origin))
        except SyncError as exc:
            raise HTTPException(status_code=400, detail=str(exc)) from exc
        if record is None:
            raise HTTPException(status_code=404, detail="Package blob is not cached")
        return client_sync_response(record)

    @app.put("/api/v1/client-sync/{kind}/{sha256}")
    async def client_sync_upload(request: Request, kind: str, sha256: str, filename: str, origin: str = ""):
        client_sync_enabled()
        try:
            record = await client_sync.upload(
                request, kind, sha256, filename, _decode_client_origin(origin)
            )
        except SyncError as exc:
            raise HTTPException(status_code=422, detail=str(exc)) from exc
        return JSONResponse(client_sync_response(record), status_code=201)

    @app.get("/api/v1/artifacts")
    async def recent_artifacts(limit: int = 100) -> dict[str, object]:
        limit = min(max(limit, 1), 1000)
        return {"artifacts": [record.__dict__ for record in store.iter_recent(limit)]}

    @app.get("/api/v1/sources/{source_id}/artifacts")
    async def source_artifacts(
        source_id: str, query: str = "", limit: int = 100, offset: int = 0
    ) -> dict[str, object]:
        if source_id not in settings.sources and dynamic_source(source_id) is None:
            raise HTTPException(status_code=404, detail=f"Unknown source: {source_id}")
        limit = min(max(limit, 1), 500)
        offset = max(offset, 0)
        query = query.strip()[:200]
        total, records = store.search_artifacts(source_id, query, limit, offset)
        return {"total": total, "artifacts": [record.__dict__ for record in records]}

    @app.get("/api/v1/pools/{pool}/artifacts")
    async def pool_artifacts(
        pool: str, query: str = "", limit: int = 100, offset: int = 0
    ) -> dict[str, object]:
        if pool not in CacheStore.VALID_POOLS:
            raise HTTPException(status_code=404, detail=f"Unknown cache pool: {pool}")
        limit = min(max(limit, 1), 500)
        offset = max(offset, 0)
        total, records = store.search_pool_artifacts(pool, query.strip()[:200], limit, offset)
        return {"total": total, "artifacts": [record.__dict__ for record in records]}

    # PEP 503 clients (including pip) request project pages with a trailing
    # slash.  Keep the slashless form too for browsers and older clients.
    @app.get("/get/pypi/{source_id}/simple/{project}/")
    @app.get("/get/pypi/{source_id}/simple/{project}")
    async def get_pypi_simple_index(request: Request, source_id: str, project: str):
        source = pypi_source(source_id)
        if not source:
            raise HTTPException(status_code=404, detail=f"Unknown PyPI source: {source_id}")
        return await pypi_index_response(request, source, project)

    @app.get("/get/pypi/external/{upstream_token}/simple/{project}/")
    @app.get("/get/pypi/external/{upstream_token}/simple/{project}")
    async def get_external_pypi_simple_index(
        request: Request, upstream_token: str, project: str
    ):
        try:
            upstream_url = _decode_dynamic_upstream(
                upstream_token
            )
        except DynamicSourceError as exc:
            raise HTTPException(status_code=403, detail=str(exc)) from exc
        row = store.ensure_dynamic_pypi_source(upstream_url)
        source = dynamic_source(str(row["source_id"]))
        assert source is not None
        return await pypi_index_response(request, source, project)

    @app.head("/get/pypi/{source_id}/files/{token}/{filename}")
    @app.get("/get/pypi/{source_id}/files/{token}/{filename}")
    async def get_pypi_artifact(
        request: Request, source_id: str, token: str, filename: str
    ):
        source = pypi_source(source_id)
        if not source:
            raise HTTPException(status_code=404, detail=f"Unknown PyPI source: {source_id}")
        try:
            # A HEAD response has no body to stream, so retain the existing
            # file-backed path. GET requests stream cache misses immediately.
            result = (
                await pypi_gateway.artifact(source, token)
                if request.method == "HEAD"
                else await pypi_gateway.artifact_streaming(source, token)
            )
        except PackageNotFound as exc:
            raise HTTPException(status_code=404, detail=f"Python package not found: {exc}") from exc
        except UpstreamUnavailable as exc:
            raise HTTPException(status_code=502, detail=f"Upstream failed: {exc}") from exc
        if isinstance(result, StreamingCacheResult):
            headers = {
                "X-Cache": result.cache_status,
                "X-Cache-Source": result.source_id,
                "Cache-Control": "public, max-age=31536000, immutable",
            }
            if result.content_length is not None:
                headers["Content-Length"] = str(result.content_length)
            return StreamingResponse(
                result.body,
                media_type=result.content_type or "application/octet-stream",
                headers=headers,
            )
        return FileResponse(
            result.file_path,
            media_type=result.record.content_type or "application/octet-stream",
            headers={
                "X-Cache": result.cache_status,
                "X-Cache-Source": result.record.source_id,
                "X-Cache-SHA256": result.record.sha256,
                "Cache-Control": "public, max-age=31536000, immutable",
            },
        )

    @app.head("/get/{source_id}/{path:path}")
    @app.get("/get/{source_id}/{path:path}")
    async def get_cached_channel_file(request: Request, source_id: str, path: str):
        source = settings.sources.get(source_id)
        if not source:
            raise HTTPException(status_code=404, detail=f"Unknown source: {source_id}")
        if source.kind != "conda":
            raise HTTPException(status_code=404, detail="Use the PyPI endpoint for this source")
        try:
            result = await gateway.get(source, path)
        except UnsafePathError as exc:
            raise HTTPException(status_code=400, detail=str(exc)) from exc
        except PackageNotFound as exc:
            raise HTTPException(status_code=404, detail=f"Package not found upstream: {exc}") from exc
        except UpstreamUnavailable as exc:
            raise HTTPException(status_code=502, detail=f"All upstreams failed: {exc}") from exc

        cache_control = "public, max-age=31536000, immutable"
        if result.record.is_metadata:
            cache_control = f"public, max-age={source.metadata_ttl_seconds}"
        headers = {
            "X-Cache": result.cache_status,
            "X-Cache-Source": result.record.source_id,
            "X-Cache-SHA256": result.record.sha256,
            "Cache-Control": cache_control,
        }
        return FileResponse(
            result.file_path,
            media_type=result.record.content_type or "application/octet-stream",
            headers=headers,
        )

    return app


try:
    app = create_app()
except ConfigurationError:
    # Importing the module for tooling should not hide the actionable config error.
    # Uvicorn imports this symbol after the operator has supplied config.yaml.
    app = None
